name: Enhanced Weekly AI x Crypto Newsletter
on:
  schedule:
    - cron: '0 9 * * 0'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode'
        default: 'false'

jobs:
  newsletter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Check Twitter API
        id: check
        run: |
          if [ -n "${{ secrets.TWITTER_BEARER_TOKEN }}" ]; then
            echo "twitter_available=true" >> $GITHUB_OUTPUT
          else
            echo "twitter_available=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Newsletter
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          USE_TWITTER: ${{ steps.check.outputs.twitter_available }}
        run: |
          WEEK_RANGE=$(date -u -d '7 days ago' '+%d.%m')-$(date -u -d '1 day ago' '+%d.%m.%Y')
          
          CONTENT="🤖 **USEROWNED.AI WEEKLY ROUNDUP [$WEEK_RANGE]**

This week in AI x Crypto developments:

**🔥 TOP DEVELOPMENTS**"

          if [ "$USE_TWITTER" = "true" ]; then
            echo "Twitter API enabled - fetching followed accounts"
            CONTENT="$CONTENT

**📱 COMMUNITY INSIGHTS**
Enhanced monitoring of AI x Crypto leaders active."
          else
            echo "Twitter API not available - using static content"
            CONTENT="$CONTENT

**📱 COMMUNITY INSIGHTS**  
Preparing enhanced community monitoring capabilities."
          fi

          CONTENT="$CONTENT

**🧠 RESEARCH & INNOVATION**
• AI agent economics advancing
• Infrastructure scaling solutions  
• Cross-chain protocols developing

**Week's win:** AI x Crypto convergence accelerating 🚀

⚡️ Links → https://linktr.ee/userownedai"

          echo "TELEGRAM_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$CONTENT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{\"chat_id\": \"-1001559796949\", \"text\": \"$TELEGRAM_MESSAGE\", \"parse_mode\": \"Markdown\"}"
