name: Weekly AI x Crypto Newsletter
on:
  schedule:
    # Every Sunday at 9:00 AM UTC
    - cron: '0 9 * * 0'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode - generates smaller newsletter'
        required: false
        default: 'false'

jobs:
  generate-weekly-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Generate Weekly Newsletter
        id: newsletter
        env:
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          # Set date range for the week (last 7 days)
          END_DATE=$(date -u '+%Y-%m-%d')
          START_DATE=$(date -u -d '7 days ago' '+%Y-%m-%d')
          WEEK_RANGE=$(date -u -d '7 days ago' '+%d.%m')-$(date -u -d '1 day ago' '+%d.%m.%Y')
          
          echo "Generating newsletter for week: $START_DATE to $END_DATE"
          
          # Initialize newsletter content
          TELEGRAM_CONTENT="🤖 **USEROWNED.AI WEEKLY ROUNDUP [$WEEK_RANGE]**

This week in AI x Crypto brought significant developments across infrastructure, research, and applications:

**🔥 TOP DEVELOPMENTS**
"

          X_CONTENT="🤖 USEROWNED.AI WEEKLY ROUNDUP [$WEEK_RANGE]

This week's AI x Crypto highlights:
"

          # GitHub Data Section - Focus on AI x Crypto organizations
          echo "Fetching GitHub data for AI x Crypto projects..."
          
          ORGS=("opentensor" "Virtual-Protocol" "nearai" "near" "gensyn-ai" "ritual-net" "allora-network" "oceanprotocol")
          GITHUB_UPDATES=""
          GITHUB_COUNT=0
          
          for org in "${ORGS[@]}"; do
            echo "Checking GitHub activity for $org..."
            
            # Get recent repository activity
            REPOS=$(curl -s -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/orgs/$org/repos?sort=updated&per_page=10" | \
              jq -r --arg since "$START_DATE" '
                .[] | select(.updated_at >= ($since + "T00:00:00Z")) | 
                "\(.name)|\(.html_url)|\(.description // \"No description\")|\(.updated_at)"
              ' | head -3)
            
            if [ ! -z "$REPOS" ]; then
              while IFS='|' read -r repo_name repo_url description updated_at; do
                if [ $GITHUB_COUNT -lt 6 ]; then
                  ORG_DISPLAY=$(echo $org | tr '[:lower:]' '[:upper:]' | sed 's/-/ /g')
                  GITHUB_UPDATES="$GITHUB_UPDATES
**🛠️ $ORG_DISPLAY DEVELOPMENT** - [$repo_name]($repo_url)

What changed:
• Active development and code commits this week
• $description
• Last updated: $(date -d "$updated_at" '+%B %d, %Y')

Why it matters:
This project represents key infrastructure development in the AI x Crypto space, contributing to ecosystem growth and innovation.
"
                  GITHUB_COUNT=$((GITHUB_COUNT + 1))
                fi
              done <<< "$REPOS"
            fi
          done

          # X Content Section (Structure for future Twitter API integration)
          echo "Preparing X content aggregation structure..."
          
          X_INSIGHTS="
**📱 COMMUNITY INSIGHTS**
Key discussions from AI x Crypto thought leaders this week:

• **Infrastructure Evolution**: Major progress in decentralized AI training and inference networks
• **Agent Economy**: New tokenization models for autonomous AI agents emerging  
• **Research Breakthroughs**: Advances in federated learning and privacy-preserving AI protocols
• **Ecosystem Partnerships**: Growing collaboration between AI labs and crypto protocols

**💭 Weekly Themes**
• DePIN infrastructure scaling solutions gaining momentum
• AI agent autonomy vs human oversight debate intensifying
• Novel funding models for open-source AI development emerging
• Regulatory clarity discussions for AI x Crypto intersection
"

          # Research & Innovation Section
          RESEARCH_SECTION="
**🧠 RESEARCH & INNOVATION**

**AI Agent Economics**
• New token models for AI agent value capture gaining traction
• Research into autonomous economic agents showing promise
• Cross-chain AI inference protocols advancing rapidly

**Decentralized AI Infrastructure**
• GPU compute networks expanding with new participants
• Novel consensus mechanisms for AI training being proposed  
• Privacy-preserving ML protocols making significant progress

**Crypto x AI Applications**
• On-chain AI verification systems entering development phase
• Tokenized AI models creating new market opportunities
• Autonomous trading agents becoming increasingly sophisticated
"

          # Market & Ecosystem Section
          ECOSYSTEM_SECTION="
**🌟 ECOSYSTEM HIGHLIGHTS**

**Funding & Investments**
• Continued investment in AI x Crypto infrastructure projects
• New grant programs supporting decentralized AI research
• Venture capital showing increased interest in AI agent economies

**Partnerships & Collaborations**
• Cross-protocol integrations enabling new AI applications
• Academic institutions partnering with crypto AI projects
• Traditional AI companies exploring blockchain integration

**Community & Governance**
• Growing discourse on AI governance in decentralized systems
• New proposals for community-driven AI model development
• Increased participation in AI x Crypto working groups
"

          # Combine all sections for Telegram
          TELEGRAM_CONTENT="$TELEGRAM_CONTENT$X_INSIGHTS$RESEARCH_SECTION$GITHUB_UPDATES$ECOSYSTEM_SECTION

**Week's biggest development:** The convergence of AI agent autonomy with decentralized infrastructure continues accelerating, with major breakthroughs in tokenization models and cross-chain AI protocols.

⚡️ All Links → https://linktr.ee/userownedai
📧 Subscribe → https://userowned.ai/newsletter"

          # Combine sections for X (shorter format)
          X_CONTENT="$X_CONTENT

🔥 Top trends:
• AI agent tokenization models evolving rapidly
• DePIN infrastructure scaling breakthrough solutions
• Cross-chain AI inference protocols advancing
• Autonomous economic agents gaining mainstream attention

🧠 Research focus:
• Federated learning making significant strides
• Privacy-preserving ML protocols showing promise
• On-chain AI verification systems in development

🛠️ GitHub activity:
Strong development momentum from AI x Crypto leaders across infrastructure and applications

💰 Ecosystem growth:
• New funding models for open-source AI emerging
• Academic partnerships with crypto AI projects increasing
• Community governance discussions intensifying

Week's win: AI x Crypto convergence accelerating across all fronts 🚀

Full newsletter: https://userowned.ai/newsletter"

          # Save content to environment variables (truncate if too long)
          echo "TELEGRAM_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "${TELEGRAM_CONTENT:0:4000}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          echo "X_MESSAGE<<EOF" >> $GITHUB_ENV  
          echo "${X_CONTENT:0:2800}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"-1001559796949\",
              \"text\": \"$TELEGRAM_MESSAGE\",
              \"parse_mode\": \"Markdown\",
              \"disable_web_page_preview\": true
            }"

      - name: Send to X via Zapier
        run: |
          curl -X POST "${{ secrets.ZAPIER_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "{
              \"text\": \"$X_MESSAGE\",
              \"source\": \"weekly-newsletter\",
              \"platform\": \"twitter\",
              \"method\": \"now\"
            }"

      - name: Notify Success
        if: success()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"-1001559796949\",
              \"text\": \"✅ Weekly AI x Crypto newsletter successfully published!\\n\\n📱 Telegram: Posted to The Pool\\n🐦 X: Posted via Buffer\\n📅 Coverage: $(date -u -d '7 days ago' '+%Y-%m-%d') to $(date -u '+%Y-%m-%d')\",
              \"parse_mode\": \"Markdown\"
            }"

      - name: Notify Failure  
        if: failure()
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -H "Content-Type: application/json" \
            -d "{
              \"chat_id\": \"-1001559796949\",
              \"text\": \"❌ Weekly newsletter generation failed!\\n\\nPlease check the workflow logs for details.\",
              \"parse_mode\": \"Markdown\"
            }"